env: "LOCAL"
http_server:
  address: "0.0.0.0:8081"
  timeout: 120s
  idle_timeout: 120s
service:
  command: "python"
  file: "C:\\go-pet-projects\\agrofront\\ag_code\\get_prediction.py"
json_storage:
  path: "C:\\go-pet-projects\\agrofront\\storage"
  prefix: "zalupa"
